name: Release Workflow

on:
  push:
    branches:
      - development
      - release-*

jobs:
  release:
    uses: epam/ai-dial-ci/.github/workflows/java_release.yml@3.1.2
    with:
      java-version: 21
    secrets: inherit

  publish-jar:
    needs: release
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew publish
        env:
          GPR_USERNAME: ${{ github.actor }}
          GPR_PASSWORD: ${{ secrets.GITHUB_TOKEN }}